# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: null
        storage_factory_id: session.storage.factory.native

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
