parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    telegram.bot_token: '%env(TELEGRAM_BOT_TOKEN)%'
    telegram.chat_id: '%env(TELEGRAM_CHAT_ID)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\TelegramService:
        autowire: false
        autoconfigure: false
        arguments:
            $botToken: '%telegram.bot_token%'
            $chatId: '%telegram.chat_id%'
            $httpClient: '@http_client'
